### PR TITLE
Modified to something that's easier to understand

### PR DESCRIPTION
**Pull request by joshuawaheed**
## Improved

- Changed filename index.js to more intuitive server.js
- Removed NPM N3 to my own function named jsonifyN3(), which I will improve. At the moment, my jsonifyN3() function is tailored to work for this demo. NPM N3 was a little bit confusing and doesn't seem to be working locally and on this app link http://aqueous-tor-14631.herokuapp.com/.
- Created a local REST API to pull data via JavaScript, which is on http://localhost:8080/mps
- Made data available via server-side rendering

## Will Improve

- jsonifyN3() to convert any N-Triples file to JSON
- How data gets added to a document

### CODE REVIEW

**Comment by mattrayner** [comment]
I like it, I'm unsure why N3 has stopped working

My only request would be moving the helpers into their own file?

other than that LGTM

**Comment by joshuawaheed** [comment]
Hi @mattrayner, Thanks for the feedback. I've made those amends by moving server.js to a folder called server with the helper functions in their own files inside a helper folder. This is the structure:

```
server
  |- helpers
    |- helpers.js
    |- jsonifyN3.js
    |- requestN3.js
  |- server.js
...
```

**Comment by mattrayner** [comment]
So, I would merge, but don't have write access...

**Comment by joshuawaheed** [comment]
Ahh, I'll see if WebOps can sort this out for us. Thanks.

**Pull request merged**
